# Generated by Django 4.2.4 on 2023-08-24 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('arthor', models.CharField(max_length=255)),
                ('cover', models.ImageField(upload_to='uploads/books/')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.collections')),
            ],
        ),
    ]
